/*
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LanguageNameUiModule extends AbstractLanguageNameUiModule {

	public LanguageNameUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
