/*
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LanguageNameRuntimeModule extends AbstractLanguageNameRuntimeModule {
}
