/*
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LanguageNameStandaloneSetup extends LanguageNameStandaloneSetupGenerated {

	public static void doSetup() {
		new LanguageNameStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
